### ISSUE TITLE
Setup fails with 301

### ISSUE THREAD

**Issue by ManInDark** [Joedmin/xExtension-wallabag-button#13]
After installing version 0.5 and trying to set config items I get an `Access request failed! Wallabag API error code: 301` error.

The Log messages produced by FreshRSS are as follows:

```
freshrss  | 192.168.1.19 - - [24/Jan/2025:13:41:26 +0100] "POST /i/?c=wallabagButton&a=requestAccess HTTP/1.1" 302 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
freshrss  | FreshRSS[40]: [manindark] [Fri, 24 Jan 2025 13:41:26 +0100] [warning] --- wallabag_client_secret does not exist in configuration
freshrss  | FreshRSS[40]: [manindark] [Fri, 24 Jan 2025 13:41:26 +0100] [warning] --- wallabag_access_token does not exist in configuration
freshrss  | FreshRSS[40]: [manindark] [Fri, 24 Jan 2025 13:41:26 +0100] [warning] --- wallabag_refresh_token does not exist in configuration
freshrss  | FreshRSS[40]: [manindark] [Fri, 24 Jan 2025 13:41:26 +0100] [warning] --- wallabag_keyboard_shortcut does not exist in configuration
freshrss  | 192.168.1.19 - - [24/Jan/2025:13:41:26 +0100] "GET /i/?c=extension&a=configure&e=Wallabag+Button&rid=67938a7612db9 HTTP/1.1" 200 3564 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
freshrss  | 192.168.1.19 - - [24/Jan/2025:13:41:26 +0100] "GET /i/?c=wallabagButton&a=jsVars HTTP/1.1" 200 311 "https://freshrss.mid/i/?c=extension&a=configure&e=Wallabag+Button&rid=67938a7612db9" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
freshrss  | [Fri Jan 24 13:41:26.156204 2025] [authz_core:error] [pid 36:tid 36] [client 192.168.1.19:0] AH01630: client denied by server configuration: /var/www/FreshRSS/p/themes/manifest.json
freshrss  | 192.168.1.19 - - [24/Jan/2025:13:41:26 +0100] "GET /themes/manifest.json HTTP/1.1" 403 199 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
```

Even though the log says otherwise I've set all config items, though I'm unsure whether my instance url is correct. I selfhost Wallabag under my own TLD as `wallabag.mid` with an selfsigned certificate, so https should work (yes the root certificate is in the store of the docker host). Therefore I set the url to `https://wallabag.mid`, but I'm not sure if that is correct.

**Comment by Joedmin** [comment]
Hi, could you please go to the extention directory and run `git pull --all && git checkout dev`. I pushed a change but I'm not sure if it fixes this.

**Comment by ManInDark** [comment]
Thanks!
This seems to have fixed the issue with the 301.

In the meantime I've started trying to configure the extension via the `config.php` in the `users` directory and it seems that the 301 had appeared because I had at some point mistakenly put `http` into the url field instead of `https`, but now both 'work' that far that I don't get a warning because of that anymore.

I still have the problem that neither the articles nor the requests show up in the wallabag log, but at this point I'm reasonably sure that there is some problem with my self signed certificates that php maybe for some reason doesn't recognize, even though I had added it to the docker host.

The only information I'm going off at this point is this: `A request has failed, it may have been caused by internet connection problems.`
Which I read as 'php doesn't accept your self signed certificates'.

**Comment by ManInDark** [comment]
Ok my therory that it's because of the certificate is pretty much confirmed.
If I change it to `http` it shows up in the wallabag log as 301 (because of automatic https upgrade configuration in nginx) but if I put in `https` it doesn't show up, so there has to be a reason why it doesn't go through with the request, which is because it doesn't accept the certificate.

**Comment by ManInDark** [comment]
I've now 'fixed' my problem like this:
```diff
diff --git a/Controllers/wallabagButtonController.php b/Controllers/wallabagButtonController.php
index b8af84d..41123e2 100644
--- a/Controllers/wallabagButtonController.php
+++ b/Controllers/wallabagButtonController.php
@@ -194,6 +194,7 @@ class FreshExtension_wallabagButton_Controller extends Minz_ActionController
     curl_setopt($curl, CURLOPT_POST, true);

     curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($post_data, JSON_UNESCAPED_UNICODE));
+    curl_setopt($curl, CURLOPT_CAINFO, "/etc/ssl/certs/root-certificate.pem");

     $response = curl_exec($curl);
     $header_size = curl_getinfo($curl, CURLINFO_HEADER_SIZE);

```
The line basically just tells curl to check that file for certificates and allow those too.

I'm not quite sure why but I still get the `A request has failed, it may have been caused by internet connection problems.` error, but as it works that is enough for me for now.

**Comment by Joedmin** [comment]
Coud you please take a look at the status code it gives you when you use your custom certificate?

**Comment by ManInDark** [comment]
```
[26-Jan-2025 16:13:24 Europe/Berlin] 0
[26-Jan-2025 16:13:24 Europe/Berlin] Status: 200
[26-Jan-2025 16:13:24 Europe/Berlin] Response: {"is_archived":0,"is_starred":0,"user_name":"wallabag","user_email":"wallabag@wallabag.io","user_id":1,"tags":[{"id":4,"label":"heise","slug":"t:heise"}],"is_public":false,"id":297,"uid":null,"title":"100 Gigawatt: Deutschland erreicht Meilenstein bei installierter Photovoltaik","url":"https:\/\/www.heise.de\/news\/Erneuerbare-Energien-100-Gigawatt-Photovoltaik-in-Deutschland-installiert-10256519.html?view=print","hashed_url":"1caa344ed74be2e082dce4ddb9bc6892f36fe71e","origin_url":"https:\/\/www.heise.de\/news\/Erneuerbare-Energien-100-Gigawatt-Photovoltaik-in-Deutschland-installiert-10256519.html?wt_mc=rss.red.ho.top-news.rdf.beitrag.beitrag","given_url":"https:\/\/www.heise.de\/news\/Erneuerbare-Energien-100-Gigawatt-Photovoltaik-in-Deutschland-installiert-10256519.html?wt_mc=rss.red.ho.top-news.rdf.beitrag.beitrag","hashed_given_url":"1ee6d9c691612c1e8eb5a431f09f1a3be8c9be7f","archived_at":null,"content":"[shortened]","created_at":"2025-01-26T15:13:24+0000","updated_at":"2025-01-26T15:13:24+0000","published_at":"2025-01-25T10:19:00+0100","published_by":["Dirk Knop"],"starred_at":null,"annotations":null,"mimetype":"text\/html; charset=UTF-8","language":"de","reading_time":2,"domain_name":"www.heise.de","preview_picture":"[shortened]","http_status":"200","headers":{"server":"nginx","date":"Sun, 26 Jan 2025 15:12:49 GMT","content-type":"text\/html; charset=UTF-8","last-modified":"Sun, 26 Jan 2025 15:12:49 GMT","age":"34","accept-ranges":"bytes","strict-transport-security":"max-age=15768000","x-frame-options":"DENY","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","x-hacc-refreshed":"","vary":"Accept-Encoding, X-Export-Format, X-Export-Agent, X-Export-IAP","cache-control":"no-store","content-length":"236096","connection":"keep-alive"},"_links":{"self":{"href":"\/api\/entries\/297"}}}
```
(I [shortened] some parts because otherwise the log would have been unreadable)
this log is the result of those log statements I inserted

```diff --git a/Controllers/wallabagButtonController.php b/Controllers/wallabagButtonController.php
--- a/Controllers/wallabagButtonController.php
+++ b/Controllers/wallabagButtonController.php
@@ -194,6 +194,7 @@ class FreshExtension_wallabagButton_Controller extends Minz_ActionController
     curl_setopt($curl, CURLOPT_POST, true);

     curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($post_data, JSON_UNESCAPED_UNICODE));
+    curl_setopt($curl, CURLOPT_CAINFO, "/etc/ssl/certs/root-certificate.pem");

     $response = curl_exec($curl);
     $header_size = curl_getinfo($curl, CURLINFO_HEADER_SIZE);
@@ -201,6 +202,11 @@ class FreshExtension_wallabagButton_Controller extends Minz_ActionController
     $response_body = substr($response, $header_size);
     $response_headers = $this->httpHeaderToArray($response_header);

+    ini_set("error_log", "/tmp/php-error.log");
+    error_log("Error Code: " . isset($response_headers['x-error-code']) ? intval($response_headers['x-error-code']) : curl_getinfo($curl, CURLINFO_HTTP_CODE));
+    error_log("Status: " . curl_getinfo($curl, CURLINFO_HTTP_CODE));
+    error_log("Response: " . $response_body);
+
     return array(
       'response' => json_decode($response_body),
       'status' => curl_getinfo($curl, CURLINFO_HTTP_CODE),

```

This doesn't make sense for me, as 200 should be an success.

**Comment by Joedmin** [comment]
I just wanted to verify something. Thanks. I'll soon release a new version with the ability to sepify path to custom certificates. I'll also add a note there about FreshRSS in Docker (which is my case) so that the paths don't have to maths

**Comment by ManInDark** [comment]
Not quite sure what exactly caused this but after setting up FreshRSS again (had an error in my setup script for the update) clicking the Wallabag Button now results in an green "Successfully added [...]" notification, so it appears to work now (with my fix applied) in FreshRSS v1.26.3.
